import React from "react";
import { Document, Page, View, Text, Image, StyleSheet, renderToBuffer } from "@react-pdf/renderer";
import { formatItemLine, type RfqDocHeader, type RfqDocItem } from "./document";
import type { PdfBranding } from "@/lib/reports/branding";

const styles = StyleSheet.create({
  page: { paddingHorizontal: 42, paddingVertical: 40, fontSize: 10, fontFamily: "Helvetica", color: "#111827" },
  header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 2 },
  headerLeft: { flexDirection: "row", alignItems: "center" },
  mark: { width: 17, height: 20, marginRight: 7 },
  eventLogo: { width: 110, height: 32, objectFit: "cover", borderRadius: 2 },
  brand: { fontSize: 9, color: "#111114" },
  h1: { fontSize: 18, marginBottom: 2 },
  sub: { fontSize: 10, color: "#6b7280", marginBottom: 16 },
  metaRow: { flexDirection: "row", marginBottom: 3 },
  metaLabel: { width: 110, color: "#6b7280" },
  metaValue: { flex: 1 },
  sectionTitle: { fontSize: 11, fontFamily: "Helvetica-Bold", marginTop: 16, marginBottom: 6 },
  itemRow: { flexDirection: "row", borderBottomWidth: 0.5, borderBottomColor: "#e5e7eb", paddingVertical: 4 },
  itemNum: { width: 22, color: "#9ca3af" },
  itemText: { flex: 1 },
  notes: { marginTop: 14, fontSize: 9, color: "#374151" },
  footer: { position: "absolute", bottom: 24, left: 42, right: 42, fontSize: 8, color: "#9ca3af", flexDirection: "row", justifyContent: "space-between" },
});

export interface RfqPdfInput {
  rfq: RfqDocHeader;
  items: RfqDocItem[];
  recipient?: { supplierName: string; contactName?: string | null } | null;
  orgName: string;
  eventName: string;
  branding?: PdfBranding;
}

function Meta({ label, value }: { label: string; value: string }) {
  return (
    <View style={styles.metaRow}>
      <Text style={styles.metaLabel}>{label}</Text>
      <Text style={styles.metaValue}>{value}</Text>
    </View>
  );
}

export async function toRfqPdf(input: RfqPdfInput): Promise<Buffer> {
  const { rfq, items, recipient, orgName, eventName, branding } = input;
  // rfq_no may already be like "RFQ-001" (M22 numbering) — don't double the prefix.
  const ref = rfq.rfqNo ? (/^rfq/i.test(rfq.rfqNo.trim()) ? rfq.rfqNo.trim() : `RFQ ${rfq.rfqNo}`) : "Request for Quote";
  const doc = (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <View style={styles.headerLeft}>
            {branding?.mark ? <Image src={branding.mark} style={styles.mark} /> : null}
            <Text style={styles.brand}>Advancer — A Kyron System · {orgName}</Text>
          </View>
          {branding?.eventImage ? <Image src={branding.eventImage} style={styles.eventLogo} /> : null}
        </View>
        <Text style={styles.h1}>{ref}</Text>
        <Text style={styles.sub}>
          {rfq.title} · {eventName}
        </Text>

        {recipient ? <Meta label="To" value={recipient.contactName ? `${recipient.contactName} — ${recipient.supplierName}` : recipient.supplierName} /> : null}
        <Meta label="Delivery date" value={rfq.deliveryDate ?? "TBC"} />
        <Meta label="Collection date" value={rfq.collectionDate ?? "TBC"} />
        {rfq.location ? <Meta label="Location" value={rfq.location} /> : null}
        <Meta label="Quote due" value={rfq.responseDueDate ?? "At your earliest convenience"} />

        <Text style={styles.sectionTitle}>Items ({items.length})</Text>
        {items.length === 0 ? (
          <Text style={{ color: "#6b7280" }}>To be confirmed.</Text>
        ) : (
          items.map((it, i) => (
            <View key={i} style={styles.itemRow} wrap={false}>
              <Text style={styles.itemNum}>{i + 1}.</Text>
              <Text style={styles.itemText}>{formatItemLine(it)}</Text>
            </View>
          ))
        )}

        {rfq.notes ? <Text style={styles.notes}>Notes: {rfq.notes}</Text> : null}

        <View style={styles.footer} fixed>
          <Text>Please return your quote ex-GST. Generated by Advancer.</Text>
          <Text render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`} />
        </View>
      </Page>
    </Document>
  );
  return Buffer.from(await renderToBuffer(doc));
}
