import React from "react";
import { Document, Page, View, Text, StyleSheet, renderToBuffer } from "@react-pdf/renderer";
import type { ReportData } from "./types";

const styles = StyleSheet.create({
  page: { paddingHorizontal: 26, paddingVertical: 24, fontSize: 8, fontFamily: "Helvetica", color: "#111827" },
  brand: { fontSize: 8, color: "#111114", marginBottom: 1 },
  title: { fontSize: 14, marginBottom: 1 },
  subtitle: { fontSize: 9, color: "#6b7280", marginBottom: 8 },
  headerRow: { flexDirection: "row", backgroundColor: "#111114", paddingVertical: 4, paddingHorizontal: 2 },
  headerCell: { color: "#ffffff", paddingHorizontal: 3 },
  row: { flexDirection: "row", borderBottomWidth: 0.5, borderBottomColor: "#e5e7eb", paddingVertical: 2.5, paddingHorizontal: 2 },
  rowAlt: { backgroundColor: "#f7f7f8" },
  cell: { paddingHorizontal: 3 },
  totalsRow: { flexDirection: "row", borderTopWidth: 1, borderTopColor: "#111827", paddingVertical: 4, paddingHorizontal: 2 },
  totalsCell: { paddingHorizontal: 3, fontFamily: "Helvetica-Bold" },
  footer: { position: "absolute", bottom: 14, left: 26, right: 26, fontSize: 7, color: "#9ca3af", flexDirection: "row", justifyContent: "space-between" },
});

function widths(report: ReportData): string[] {
  const weights = report.columns.map((c) => Math.max(6, c.label.length));
  const total = weights.reduce((a, b) => a + b, 0);
  return weights.map((w) => `${((w / total) * 100).toFixed(2)}%`);
}

function ColText({ value, align }: { value: unknown; align?: "right" | "center" }) {
  return <Text style={{ textAlign: align ?? "left" }}>{String(value ?? "")}</Text>;
}

function Section({ report, eventName }: { report: ReportData; eventName: string }) {
  const w = widths(report);
  return (
    <>
      <Text style={styles.brand}>Advancer — A Kyron System · {eventName}</Text>
      <Text style={styles.title}>{report.title}</Text>
      {report.subtitle ? <Text style={styles.subtitle}>{report.subtitle}</Text> : null}
      <View style={styles.headerRow} fixed>
        {report.columns.map((c, i) => (
          <View key={c.key} style={{ width: w[i] }}>
            <Text style={[styles.headerCell, { textAlign: c.align ?? "left" }]}>{c.label}</Text>
          </View>
        ))}
      </View>
      {report.rows.map((r, ri) => (
        <View key={ri} style={[styles.row, ...(ri % 2 ? [styles.rowAlt] : [])]} wrap={false}>
          {report.columns.map((c, i) => (
            <View key={c.key} style={[styles.cell, { width: w[i] }]}>
              <ColText value={r[c.key]} align={c.align} />
            </View>
          ))}
        </View>
      ))}
      {report.totals ? (
        <View style={styles.totalsRow} wrap={false}>
          {report.columns.map((c, i) => (
            <View key={c.key} style={[styles.totalsCell, { width: w[i] }]}>
              <Text style={{ textAlign: c.align ?? "left", fontFamily: "Helvetica-Bold" }}>
                {String(report.totals![c.key] ?? "")}
              </Text>
            </View>
          ))}
        </View>
      ) : null}
    </>
  );
}

function Footer() {
  return (
    <View style={styles.footer} fixed>
      <Text>Generated by Advancer</Text>
      <Text render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`} />
    </View>
  );
}

export async function toPdf(report: ReportData, eventName: string): Promise<Buffer> {
  const doc = (
    <Document>
      <Page size="A4" orientation="landscape" style={styles.page}>
        <Section report={report} eventName={eventName} />
        <Footer />
      </Page>
    </Document>
  );
  return Buffer.from(await renderToBuffer(doc));
}

export async function toEventPackPdf(reports: ReportData[], eventName: string): Promise<Buffer> {
  const doc = (
    <Document>
      {reports.map((report, i) => (
        <Page key={i} size="A4" orientation="landscape" style={styles.page}>
          <Section report={report} eventName={eventName} />
          <Footer />
        </Page>
      ))}
    </Document>
  );
  return Buffer.from(await renderToBuffer(doc));
}
